Dockerfile, README.md, client/src/App.tsx, client/src/api/auth.ts, client/src/api/snippets.ts, client/src/components/auth/LoginPage.tsx, client/src/components/snippets/SnippetStorage.tsx, client/src/context/AuthContext.tsx, client/src/hooks/useSnippets.ts, docker-compose.yaml, package-lock.json, server/package.json, server/src/app.js, server/src/middleware/auth.js, server/src/routes/authRoutes.js
=> [7] Add basic authentication

client/package.json, client/src/components/changelog/ChangelogModal.tsx, client/src/components/common/Modal.tsx, client/src/components/settings/SettingsModal.tsx, client/src/components/snippets/CodeEditor.tsx, client/src/components/snippets/EditSnippetModal.tsx, client/src/components/snippets/FragmentEditor.tsx, client/src/components/snippets/FullCodeBlock.tsx, client/src/components/snippets/PreviewCodeBlock.tsx, client/src/components/snippets/SnippetCard.tsx, client/src/components/snippets/SnippetModal.tsx, client/src/components/snippets/SnippetStorage.tsx, client/src/index.css, client/src/types/types.ts, package-lock.json, server/src/config/database.js, server/src/repositories/snippetRepository.js, server/src/routes/snippetRoutes.js, server/src/services/snippetService.js
Snippets can now have multiple fragments made up of multiple languages / files
Still needs some work, definitely in a testable state though, will migrate the database automatically so when testing definitely make a backup first
=> Added fragments

client/src/components/snippets/SnippetModal.tsx
Fixes #46
Removing the "trucate" class did the job.
=> fixed text overflow issue.

client/src/App.tsx, client/src/api/snippets.ts, client/src/components/snippets/FullCodeView.tsx, client/src/components/snippets/SnippetCard.tsx, client/src/components/snippets/SnippetPage.tsx, server/src/repositories/snippetRepository.js, server/src/routes/snippetRoutes.js, server/src/services/snippetService.js
Also added an API route for getting a single snippet.
=> Re-used the shared view to create a full code view, can still use the modal if preferred

.gitignore, client/src/App.tsx, client/src/components/auth/LoginPage.tsx, client/src/components/auth/oidc/OIDCCallback.tsx, client/src/constants/routes.ts, client/src/contexts/AuthContext.tsx, docker-compose.yaml, package-lock.json, server/package.json, server/src/app.js, server/src/config/database.js, server/src/config/migrations/20241111-migration.js, server/src/config/migrations/20241117-migration.js, server/src/config/migrations/20241119-migration.js, server/src/config/migrations/20241120-migration.js, server/src/logger.js, server/src/middleware/auth.js, server/src/oidc/oidcConfig.js, server/src/repositories/shareRepository.js, server/src/repositories/snippetRepository.js, server/src/repositories/userRepository.js, server/src/routes/authRoutes.js, server/src/routes/oidcRoutes.js, server/src/routes/publicRoutes.js, server/src/routes/shareRoutes.js, server/src/routes/snippetRoutes.js, server/src/services/snippetService.js, server/src/services/userService.js
Tested with Authentik, cannot comment on other providers.
=> [84] Single Sign-on

client/src/components/auth/UserDropdown.tsx, client/src/constants/settings.ts, client/src/contexts/AuthContext.tsx, client/src/types/user.ts, client/src/utils/api/auth.ts, docker-compose.yaml, server/src/middleware/auth.js, server/src/repositories/snippetRepository.js, server/src/repositories/userRepository.js, server/src/routes/authRoutes.js, server/src/services/snippetService.js
It acts as a fully authenticated user, it just logs in automatically. Old snippets should be transferred by exporting from the old account and importing to the anonymous account.
=> Added disable accounts option

server/src/routes/oidcRoutes.js
=> [145] Fix OIDC under base path

client/package.json, client/src/components/snippets/list/SnippetCard.tsx, client/src/components/snippets/view/FullCodeView.tsx, client/src/constants/linkify.ts, package-lock.json
=> [80] Added support for markdown descriptions & removed linkify

client/src/components/common/modals/Modal.tsx
=> [feat] added escape to close functionality

server/src/repositories/userRepository.js
=> [feat] prefer name over email substring

client/src/components/common/modals/Modal.tsx
=> [feat] remember the expansion state of modals

client/src/components/settings/SettingsModal.tsx, client/src/components/snippets/view/common/StorageHeader.tsx, client/src/utils/paths.ts, server/src/app.js
=> [bug] fixed assets under base path

client/src/constants/settings.ts
=> [bug] fix app version number

helm-charts/bytestash/.example.yaml, helm-charts/bytestash/.helmignore, helm-charts/bytestash/Chart.yaml, helm-charts/bytestash/README.md, helm-charts/bytestash/templates/NOTES.txt, helm-charts/bytestash/templates/_helpers.tpl, helm-charts/bytestash/templates/deployment.yaml, helm-charts/bytestash/templates/ingress.yaml, helm-charts/bytestash/templates/pvc.yaml, helm-charts/bytestash/templates/service.yaml, helm-charts/bytestash/templates/serviceaccount.yaml, helm-charts/bytestash/values.yaml
Dear @jordan-dalby ,
This is a helm chart for ByteStash that I've written, tested, and deployed to my Kubernetes cluster. 
This PR will resolve issue #174 
I've also included a README file and an example file in the PR. Please have a look.
**NOTE**: I had set this chart to use ByteStash image version `1.5.7` by default.
Thank you,
=> Propose to add ByteStash Helm Chart

client/src/index.css
=> [feat] add colour to clickable links in markdown

client/src/components/snippets/list/SnippetCard.tsx, client/src/components/snippets/list/SnippetCardMenu.tsx
=> [bug] fixed missing settings when snippetcards were small

Dockerfile, package.json, server/package.json, server/src/oidc/oidcConfig.js
=> [feat] upped node.js version to v22

client/src/components/auth/LoginPage.tsx, client/src/components/auth/RegisterPage.tsx
=> [bug] fix a bug with OIDC on bare metal

client/src/components/search/SearchAndFilter.tsx, client/src/components/search/SearchBar.tsx, client/src/constants/settings.ts
=> [feat] clear search result

client/src/components/auth/ChangePasswordModal.tsx, client/src/components/auth/UserDropdown.tsx, client/src/types/user.ts, client/src/utils/api/auth.ts, docker-compose.yaml, server/src/middleware/auth.js, server/src/repositories/userRepository.js, server/src/routes/authRoutes.js, server/src/services/userService.js
A new environment variable is introduced `ALLOW_PASSWORD_CHANGES` to indicate whether this functionality should be enabled. It is false by default for scenarios such as the demo server where password changes should be disabled.
Closes #175
=> [175] Allow changing password if current password is known

client/src/components/common/modals/Modal.tsx, client/src/components/snippets/view/SnippetModal.tsx, client/src/components/snippets/view/common/BaseSnippetStorage.tsx
Closes https://github.com/jordan-dalby/ByteStash/issues/187
=> [187] Add Edit and Delete buttons to Snippet View Modal

client/src/components/auth/ApiKeysModal.tsx
Closes https://github.com/jordan-dalby/ByteStash/issues/220
=> [220] fix: Do not show previous API key on dialog open

client/package.json, client/vite.config.ts, package-lock.json, package.json
Upgraded vite and it's plugins, lucide-react, prismjs.
Removed unused packages from project root
=> chore: Upgrade packages

server/docs/swagger.yaml, server/src/routes/apiSnippetRoutes.js
This pull request enhances the API for managing code snippets by adding new endpoints, improving validation, and restructuring some existing logic. The changes primarily focus on expanding functionality and improving data handling.
* **New Endpoints Added**:
- Added a `GET /api/v1/snippets/search` endpoint to search snippets with support for filtering and sorting by various criteria. [[1]](diffhunk://#diff-ad8b426006b1a734a96e5c323d17d70497244e48d35fd9ffa8df11d62aca5be4R737-R776) [[2]](diffhunk://#diff-0b940c1eadee106e0185050d8f6cd98d4253c62cd4f424bf59dca98d60adc31dR24-R64)
- Added a `PUT /api/v1/snippets/{id}` endpoint to update snippets by ID, including support for multipart form data. [[1]](diffhunk://#diff-ad8b426006b1a734a96e5c323d17d70497244e48d35fd9ffa8df11d62aca5be4R803-R881) …
=> Improved API routes for CRUD actions and search capabilities.

client/src/components/auth/LoginPage.tsx
Normal View : 
Show Password : 
Closes #241
=> [241] feat: Add show/hide password toggle in login page

client/src/components/categories/CategoryList.tsx, client/src/components/search/SearchAndFilter.tsx, client/src/components/snippets/edit/EditSnippetModal.tsx, client/src/components/snippets/list/SnippetCard.tsx, client/src/components/snippets/list/SnippetCardMenu.tsx, client/src/components/snippets/list/SnippetList.tsx, client/src/components/snippets/view/SnippetStorage.tsx, client/src/components/snippets/view/common/BaseSnippetStorage.tsx, client/src/components/snippets/view/public/PublicSnippetStorage.tsx, client/src/hooks/useSettings.ts, client/src/hooks/useSnippets.ts, client/src/service/snippetService.ts, client/src/types/snippets.ts, client/src/utils/api/snippets.ts, server/src/config/database.js, server/src/config/migrations/20250905-migration.js, server/src/config/schema/init.sql, server/src/repositories/snippetRepository.js, server/src/routes/snippetRoutes.js, server/src/services/snippetService.js
This PR introduces support for pinning/unpinning and favoriting/unfavoriting snippets.  
It provides users with better organization and quicker access to frequently used snippets.
- **Pin/Unpin Snippets**  
- Pinned snippets are always displayed at the top of the list.  
- Multiple pinned snippets are ordered by their last updated time.  
- **Favorite/Unfavorite Snippets**  
- Allows user to add snippets to favorites and removing from favorites.
- Favorites can be filtered and displayed separately.  
- [Video Demo](https://drive.google.com/file/d/1OGALPUlkA2MdfqXF5qXucBeVnUR7hlBF/view?usp=sharing) – showcases pin/unpin and favorite/unfavorite in action.
Fixes #93
=> feat(snippets): add pin/unpin and favorite/unfavorite functionality (#93)
